/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:345080271cbdf981ea6b6fad0d547834:cc69781c3fef1a612b1e2f6b8d59219c:14b7cfdaca6f575dd3375179a1c0b2cf$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class vamp_3_4
	{
		public const string Vamp_l_3_4_0001 = "vamp_l_3_4_0001";
		public const string Vamp_l_3_4_0002 = "vamp_l_3_4_0002";
		public const string Vamp_l_3_4_0003 = "vamp_l_3_4_0003";
		public const string Vamp_l_3_4_0004 = "vamp_l_3_4_0004";
		public const string Vamp_l_3_4_0005 = "vamp_l_3_4_0005";
		public const string Vamp_l_3_4_0006 = "vamp_l_3_4_0006";
		public const string Vamp_l_3_4_0007 = "vamp_l_3_4_0007";
		public const string Vamp_l_3_4_0008 = "vamp_l_3_4_0008";
		public const string Vamp_l_3_4_0009 = "vamp_l_3_4_0009";
		public const string Vamp_l_3_4_0010 = "vamp_l_3_4_0010";
		public const string Vamp_l_3_4_0011 = "vamp_l_3_4_0011";
		public const string Vamp_l_3_4_0012 = "vamp_l_3_4_0012";
		public const string Vamp_l_3_4_0013 = "vamp_l_3_4_0013";
		public const string Vamp_l_3_4_0014 = "vamp_l_3_4_0014";
		public const string Vamp_l_3_4_0015 = "vamp_l_3_4_0015";
		public const string Vamp_l_3_4_0016 = "vamp_l_3_4_0016";
		public const string Vamp_l_3_4_0017 = "vamp_l_3_4_0017";
		public const string Vamp_l_3_4_0018 = "vamp_l_3_4_0018";
		public const string Vamp_l_3_4_0019 = "vamp_l_3_4_0019";
		public const string Vamp_l_3_4_0020 = "vamp_l_3_4_0020";
		public const string Vamp_l_3_4_0021 = "vamp_l_3_4_0021";
		public const string Vamp_l_3_4_0022 = "vamp_l_3_4_0022";
		public const string Vamp_l_3_4_0023 = "vamp_l_3_4_0023";
		public const string Vamp_l_3_4_0024 = "vamp_l_3_4_0024";
		public const string Vamp_l_3_4_0025 = "vamp_l_3_4_0025";
		public const string Vamp_l_3_4_0026 = "vamp_l_3_4_0026";
		public const string Vamp_l_3_4_0027 = "vamp_l_3_4_0027";
		public const string Vamp_l_3_4_0028 = "vamp_l_3_4_0028";
		public const string Vamp_l_3_4_0029 = "vamp_l_3_4_0029";
		public const string Vamp_l_3_4_0030 = "vamp_l_3_4_0030";
		public const string Vamp_l_3_4_0031 = "vamp_l_3_4_0031";
		public const string Vamp_l_3_4_0032 = "vamp_l_3_4_0032";
		public const string Vamp_l_3_4_0033 = "vamp_l_3_4_0033";
	}
}